services:
  app:
    build: .
    container_name: vehicles_api_app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=vehicles_db
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:6.0
    container_name: vehicles_api_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
